var regions={
"abandonned Wilding Village":{region:"beyond the wall", coords:[926,136]},
"Acorn Hall":{region:"Riverlands", coords:[777,1227]},
"Andalos":{region:"Essos", coords:[1517,1033]},
"Astapor":{region:"Slaver's Bay", coords:[2670,1978]},
"West of the Iron Islands":{region:"Iron Islands", coords:[161,1050]},
"Barrowton":{region:"the North", coords:[652,709]},
"Bitterbridge":{region:"the Reach", coords:[770,1524]},
"Blackwater Bay":{region:"Crownlands", coords:[1021,1409]},
"Braavos":{region:"Essos", coords:[1471,943]},
"camp around the Twins":{region:"Riverlands", coords:[775,997]},
"camp near the Trident":{region:"Riverlands", coords:[900,1158]},
"Cape Wrath":{region:"Stormlands", coords:[1114,1704]},
"Castle Black":{region:"the Wall", coords:[955,169]},
"Castle Darry":{region:"Riverlands", coords:[939,1193]},
"Castle Hayford":{region:"Crownlands", coords:[955,1370]},
"Castle Rosby":{region:"Crownlands", coords:[1017,1326]},
"Cave of Beric Dondarrion":{region:"Riverlands", coords:[987,1264]},
"Cave of the Children of the Forest":{region:"beyond the wall", coords:[858,128]},
"cavern in haunted forest":{region:"beyond the wall", coords:[822,108]},
"Craster's Keep":{region:"beyond the wall", coords:[907,131]},
"Deepwood Motte":{region:"the North", coords:[643,381]},
"deserted wildling village":{region:"beyond the wall", coords:[1031,109]},
"Dorne":{region:"Dorne", coords:[859,1876]},
"Dothraki Sea":{region:"Essos", coords:[2774,1531]},
"Dragonstone":{region:"Crownlands", coords:[1186,1295]},
"Dragonstone (Essos)":{region:"Essos", coords:[3021,1612]},
"Dreadfort":{region:"the North", coords:[1024,467]},
"Duskendale":{region:"Crownlands", coords:[1088,1284]},
"Eastwatch":{region:"the Wall", coords:[1038,178]},
"Encounter with the Brave Companions":{region:"Riverlands", coords:[904,1157]},
"field outside of Pentos":{region:"Essos", coords:[1524,1378]},
"Fishing village east of God's eye":{region:"Riverlands", coords:[926,1252]},
"Fist of the First Men":{region:"beyond the wall", coords:[840,92]},
"Gates of the Moon":{region:"the Vale", coords:[1022,1093]},
"Ghoyan Drohe":{region:"Essos", coords:[1678,1401]},
"Green Fork":{region:"Riverlands", coords:[938,1075]},
"Greywater Watch":{region:"the North", coords:[787,788]},
"Gulf of Grief":{region:"Slaver's Bay", coords:[2532,2169]},
"Hammerhorn":{region:"Iron Islands", coords:[442,1044]},
"Hardhome":{region:"beyond the wall", coords:[1075,58]},
"Harrenhal":{region:"Riverlands", coords:[893,1222]},
"Haunted Forest":{region:"beyond the wall", coords:[916,116]},
"High Heart":{region:"Riverlands", coords:[789,1213]},
"High Road (in Mountains of the Moon)":{region:"the Vale", coords:[953,1153]},
"High Road (near the Eyrie)":{region:"the Vale", coords:[1016,1101]},
"Holdfast on west shore of God's eye":{region:"Riverlands", coords:[873,1260]},
"Inn of the Kneeling Man":{region:"Riverlands", coords:[791,1141]},
"Inn south of the God's eye":{region:"Riverlands", coords:[900,1319]},
"Isle of Cedars":{region:"Slaver's Bay", coords:[2662,1883]},
"Khal Drogo's manse":{region:"Essos", coords:[1505,1385]},
"King's Landing":{region:"Crownlands", coords:[1277,1642]},
"Kingsroad, a little north of King's Landing":{region:"Crownlands", coords:[984,1325]},
"kingsroad, north of Winterfell":{region:"the North", coords:[938,297]},
"kingsroad, south of Winterfell":{region:"the North", coords:[813,670]},
"Lhazareen village":{region:"Essos", coords:[2868,1677]},
"Little Finger":{region:"the Vale", coords:[1208,924]},
"Lordsport":{region:"Iron Islands", coords:[484,1101]},
"Lys":{region:"Essos", coords:[1393,1944]},
"Maidenpool":{region:"Riverlands", coords:[1032,1251]},
"Frostfangs":{region:"beyond the wall", coords:[789,107]},
"Meereen":{region:"Slaver's Bay", coords:[2752,1752]},
"Mill on Acorn Water":{region:"the North", coords:[793,563]},
"Moat Cailin":{region:"the North", coords:[820,754]},
"Mole's Town":{region:"the North", coords:[958,204]},
"Mountains of the Moon":{region:"the Vale", coords:[1021,1117]},
"Nagga's Hills":{region:"Iron Islands", coords:[423,1033]},
"New Ghis":{region:"Slaver's Bay", coords:[2735,2350]},
"Nightfort":{region:"the Wall", coords:[1033,171]},
"North of Harrenhal":{region:"Riverlands", coords:[893,1195]},
"North of Tumbledown tower":{region:"the North", coords:[746,352]},
"Ny Sar":{region:"Essos", coords:[1753,1456]},
"off the coast of Dorne":{region:"Dorne", coords:[1318,1874]},
"off the coast of Valyria":{region:"Slaver's Bay", coords:[2309,2299]},
"Old Crossroads Inn":{region:"Riverlands", coords:[929,1162]},
"Old Wyk":{region:"Iron Islands", coords:[425,1035]},
"Oldstones":{region:"Riverlands", coords:[752,1060]},
"Oldtown":{region:"the Reach", coords:[485,1792]},
"outside of Harrenhal":{region:"Riverlands", coords:[897,1209]},
"Pebbleton":{region:"Iron Islands", coords:[458,1052]},
"Pennytree":{region:"Riverlands", coords:[773,1162]},
"Pentos":{region:"Essos", coords:[1487,1396]},
"Pyke":{region:"Iron Islands", coords:[504,1093]},
"Qarth":{region:"Essos", coords:[3535,2151]},
"Queenscrown":{region:"the Wall", coords:[920,206]},
"Quiet Isle":{region:"Riverlands", coords:[993,1207]},
"Raventree Hall":{region:"Riverlands", coords:[735,1139]},
"Red Fork":{region:"Riverlands", coords:[793,1145]},
"Red Waste":{region:"Essos", coords:[3004,1812]},
"Riverrun":{region:"Riverlands", coords:[732,1177]},
"Saltpans":{region:"Riverlands", coords:[969,1196]},
"Seagard":{region:"Riverlands", coords:[742,1024]},
"Selhorys":{region:"Essos", coords:[1826,1782]},
"Shield Islands":{region:"the Reach", coords:[479,1598]},
"Skagos":{region:"the North", coords:[1183,195]},
"Skirling pass":{region:"beyond the wall", coords:[801,94]},
"Slaver's Bay":{region:"Slaver's Bay", coords:[2564,1879]},
"south of Craster's Keep":{region:"beyond the wall", coords:[911,147]},
"Stone Mill":{region:"Riverlands", coords:[770,1160]},
"Stoney Sept":{region:"Riverlands", coords:[794,1313]},
"Stony Shore":{region:"the North", coords:[404,593]},
"Storm's end":{region:"Stormlands", coords:[1114,1585]},
"Sunspear":{region:"Dorne", coords:[1208,1923]},
"Ten Towers":{region:"Iron Islands", coords:[569,1070]},
"The Crag":{region:"Westerlands", coords:[526,1194]},
"the Eyrie":{region:"the Vale", coords:[1068,1062]},
"the Greenblood":{region:"Dorne", coords:[1082,1910]},
"The Peach Inn":{region:"Riverlands", coords:[790,1314]},
"the Sorrows":{region:"Essos", coords:[1813,1642]},
"the Twins":{region:"Riverlands", coords:[764,980]},
"The Wall, spot of first invasion":{region:"the Wall", coords:[911,166]},
"the Whispers":{region:"Crownlands", coords:[1197,1214]},
"Town held by Bloody Mummers":{region:"Riverlands", coords:[936,1181]},
"Trident ferry":{region:"Riverlands", coords:[917,1174]},
"Tumbledown tower":{region:"the North", coords:[714,472]},
"Vaes Dothrak":{region:"Essos", coords:[3182,1210]},
"Vaes Tolorro":{region:"Essos", coords:[3096,1826]},
"Village between the lakes":{region:"the North", coords:[914,327]},
"Village of lord Goodbrook":{region:"Riverlands", coords:[823,1199]},
"Village that rests in the trees":{region:"Riverlands", coords:[845,1210]},
"Volantis":{region:"Essos", coords:[1909,1926]},
"Volon Therys":{region:"Essos", coords:[1874,1917]},
"Water gardens":{region:"Dorne", coords:[1199,1932]},
"Weirwood north of the Wall":{region:"beyond the wall", coords:[960,156]},
"Whispering Wood":{region:"Riverlands", coords:[739,1190]},
"White Harbor":{region:"the North", coords:[913,717]},
"Whitetree":{region:"beyond the wall", coords:[930,156]},
"Wilding ambush site":{region:"beyond the wall", coords:[812,92]},
"Winterfell":{region:"the North", coords:[807,505]},
"Wolfswood":{region:"the North", coords:[678,453]},
"Yunkai":{region:"Slaver's Bay", coords:[2701,1812]},
"Giant's stairs":{region:"beyond the wall", coords:[807,77]},
"Milkwater":{region:"beyond the wall", coords:[788,71]},
"Shadow Tower":{region:"the Wall", coords:[861,171]},
"Torrhen's Square":{region:"the North};", coords:[672,583]},
"Norvos":{region:"Essos", coords:[1744,1230]},
"Tyrosh":{region:"Essos", coords:[1382,1697]},
"Greenstone":{region:"Stormlands", coords:[1214,1701]},
"Longtable":{region:"the Reach", coords:[744,1564]}

};

var chapters=[
{id:0,bookId:0,chapterInBook:0, povId:1825, povName:"Will",title:"Prologue"},
{id:1,bookId:0,chapterInBook:1, povId:240, povName:"Bran Stark",title:"Bran I"},
{id:2,bookId:0,chapterInBook:2, povId:287, povName:"Catelyn Tully",title:"Catelyn I"},
{id:3,bookId:0,chapterInBook:3, povId:352, povName:"Daenerys Targaryen",title:"Daenerys I"},
{id:4,bookId:0,chapterInBook:4, povId:456, povName:"Eddard Stark",title:"Eddard I"},
{id:5,bookId:0,chapterInBook:5, povId:851, povName:"Jon Snow",title:"Jon I"},
{id:6,bookId:0,chapterInBook:6, povId:287, povName:"Catelyn Tully",title:"Catelyn II"},
{id:7,bookId:0,chapterInBook:7, povId:136, povName:"Arya Stark",title:"Arya I"},
{id:8,bookId:0,chapterInBook:8, povId:240, povName:"Bran Stark",title:"Bran II"},
{id:9,bookId:0,chapterInBook:9, povId:1716, povName:"Tyrion Lannister",title:"Tyrion I"},
{id:10,bookId:0,chapterInBook:10, povId:851, povName:"Jon Snow",title:"Jon II"},
{id:11,bookId:0,chapterInBook:11, povId:352, povName:"Daenerys Targaryen",title:"Daenerys II"},
{id:12,bookId:0,chapterInBook:12, povId:456, povName:"Eddard Stark",title:"Eddard II"},
{id:13,bookId:0,chapterInBook:13, povId:1716, povName:"Tyrion Lannister",title:"Tyrion II"},
{id:14,bookId:0,chapterInBook:14, povId:287, povName:"Catelyn Tully",title:"Catelyn III"},
{id:15,bookId:0,chapterInBook:15, povId:1530, povName:"Sansa Stark",title:"Sansa I"},
{id:16,bookId:0,chapterInBook:16, povId:456, povName:"Eddard Stark",title:"Eddard III"},
{id:17,bookId:0,chapterInBook:17, povId:240, povName:"Bran Stark",title:"Bran III"},
{id:18,bookId:0,chapterInBook:18, povId:287, povName:"Catelyn Tully",title:"Catelyn IV"},
{id:19,bookId:0,chapterInBook:19, povId:851, povName:"Jon Snow",title:"Jon III"},
{id:20,bookId:0,chapterInBook:20, povId:456, povName:"Eddard Stark",title:"Eddard IV"},
{id:21,bookId:0,chapterInBook:21, povId:1716, povName:"Tyrion Lannister",title:"Tyrion III"},
{id:22,bookId:0,chapterInBook:22, povId:136, povName:"Arya Stark",title:"Arya II"},
{id:23,bookId:0,chapterInBook:23, povId:352, povName:"Daenerys Targaryen",title:"Daenerys III"},
{id:24,bookId:0,chapterInBook:24, povId:240, povName:"Bran Stark",title:"Bran IV"},
{id:25,bookId:0,chapterInBook:25, povId:456, povName:"Eddard Stark",title:"Eddard V"},
{id:26,bookId:0,chapterInBook:26, povId:851, povName:"Jon Snow",title:"Jon IV"},
{id:27,bookId:0,chapterInBook:27, povId:456, povName:"Eddard Stark",title:"Eddard VI"},
{id:28,bookId:0,chapterInBook:28, povId:287, povName:"Catelyn Tully",title:"Catelyn V"},
{id:29,bookId:0,chapterInBook:29, povId:1530, povName:"Sansa Stark",title:"Sansa II"},
{id:30,bookId:0,chapterInBook:30, povId:456, povName:"Eddard Stark",title:"Eddard VII"},
{id:31,bookId:0,chapterInBook:31, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IV"},
{id:32,bookId:0,chapterInBook:32, povId:136, povName:"Arya Stark",title:"Arya III"},
{id:33,bookId:0,chapterInBook:33, povId:456, povName:"Eddard Stark",title:"Eddard VIII"},
{id:34,bookId:0,chapterInBook:34, povId:287, povName:"Catelyn Tully",title:"Catelyn VI"},
{id:35,bookId:0,chapterInBook:35, povId:456, povName:"Eddard Stark",title:"Eddard IX"},
{id:36,bookId:0,chapterInBook:36, povId:352, povName:"Daenerys Targaryen",title:"Daenerys IV"},
{id:37,bookId:0,chapterInBook:37, povId:240, povName:"Bran Stark",title:"Bran V"},
{id:38,bookId:0,chapterInBook:38, povId:1716, povName:"Tyrion Lannister",title:"Tyrion V"},
{id:39,bookId:0,chapterInBook:39, povId:456, povName:"Eddard Stark",title:"Eddard X"},
{id:40,bookId:0,chapterInBook:40, povId:287, povName:"Catelyn Tully",title:"Catelyn VII"},
{id:41,bookId:0,chapterInBook:41, povId:851, povName:"Jon Snow",title:"Jon V"},
{id:42,bookId:0,chapterInBook:42, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VI"},
{id:43,bookId:0,chapterInBook:43, povId:456, povName:"Eddard Stark",title:"Eddard XI"},
{id:44,bookId:0,chapterInBook:44, povId:1530, povName:"Sansa Stark",title:"Sansa III"},
{id:45,bookId:0,chapterInBook:45, povId:456, povName:"Eddard Stark",title:"Eddard XII"},
{id:46,bookId:0,chapterInBook:46, povId:352, povName:"Daenerys Targaryen",title:"Daenerys V"},
{id:47,bookId:0,chapterInBook:47, povId:456, povName:"Eddard Stark",title:"Eddard XIII"},
{id:48,bookId:0,chapterInBook:48, povId:851, povName:"Jon Snow",title:"Jon VI"},
{id:49,bookId:0,chapterInBook:49, povId:456, povName:"Eddard Stark",title:"Eddard XIV"},
{id:50,bookId:0,chapterInBook:50, povId:136, povName:"Arya Stark",title:"Arya IV"},
{id:51,bookId:0,chapterInBook:51, povId:1530, povName:"Sansa Stark",title:"Sansa IV"},
{id:52,bookId:0,chapterInBook:52, povId:851, povName:"Jon Snow",title:"Jon VII"},
{id:53,bookId:0,chapterInBook:53, povId:240, povName:"Bran Stark",title:"Bran VI"},
{id:54,bookId:0,chapterInBook:54, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VI"},
{id:55,bookId:0,chapterInBook:55, povId:287, povName:"Catelyn Tully",title:"Catelyn VIII"},
{id:56,bookId:0,chapterInBook:56, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VII"},
{id:57,bookId:0,chapterInBook:57, povId:1530, povName:"Sansa Stark",title:"Sansa V"},
{id:58,bookId:0,chapterInBook:58, povId:456, povName:"Eddard Stark",title:"Eddard XV"},
{id:59,bookId:0,chapterInBook:59, povId:287, povName:"Catelyn Tully",title:"Catelyn IX"},
{id:60,bookId:0,chapterInBook:60, povId:851, povName:"Jon Snow",title:"Jon VIII"},
{id:61,bookId:0,chapterInBook:61, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VII"},
{id:62,bookId:0,chapterInBook:62, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VIII"},
{id:63,bookId:0,chapterInBook:63, povId:287, povName:"Catelyn Tully",title:"Catelyn X"},
{id:64,bookId:0,chapterInBook:64, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VIII"},
{id:65,bookId:0,chapterInBook:65, povId:136, povName:"Arya Stark",title:"Arya V"},
{id:66,bookId:0,chapterInBook:66, povId:240, povName:"Bran Stark",title:"Bran VII"},
{id:67,bookId:0,chapterInBook:67, povId:1530, povName:"Sansa Stark",title:"Sansa VI"},
{id:68,bookId:0,chapterInBook:68, povId:352, povName:"Daenerys Targaryen",title:"Daenerys IX"},
{id:69,bookId:0,chapterInBook:69, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IX"},
{id:70,bookId:0,chapterInBook:70, povId:851, povName:"Jon Snow",title:"Jon IX"},
{id:71,bookId:0,chapterInBook:71, povId:287, povName:"Catelyn Tully",title:"Catelyn XI"},
{id:72,bookId:0,chapterInBook:72, povId:352, povName:"Daenerys Targaryen",title:"Daenerys X"},

{id:73,bookId:1,chapterInBook:0, povId:1046, povName:"Maester Cressen",title:"Prologue"},
{id:74,bookId:1,chapterInBook:1, povId:136, povName:"Arya Stark",title:"Arya I"},
{id:75,bookId:1,chapterInBook:2, povId:1530, povName:"Sansa Stark",title:"Sansa I"},
{id:76,bookId:1,chapterInBook:3, povId:1716, povName:"Tyrion Lannister",title:"Tyrion I"},
{id:77,bookId:1,chapterInBook:4, povId:240, povName:"Bran Stark",title:"Bran I"},
{id:78,bookId:1,chapterInBook:5, povId:136, povName:"Arya Stark",title:"Arya II"},
{id:79,bookId:1,chapterInBook:6, povId:851, povName:"Jon Snow",title:"Jon I"},
{id:80,bookId:1,chapterInBook:7, povId:287, povName:"Catelyn Tully",title:"Catelyn I"},
{id:81,bookId:1,chapterInBook:8, povId:1716, povName:"Tyrion Lannister",title:"Tyrion II"},
{id:82,bookId:1,chapterInBook:9, povId:136, povName:"Arya Stark",title:"Arya III"},
{id:83,bookId:1,chapterInBook:10, povId:385, povName:"Davos Seaworth",title:"Davos I"},
{id:84,bookId:1,chapterInBook:11, povId:1648, povName:"Theon Greyjoy",title:"Theon I"},
{id:85,bookId:1,chapterInBook:12, povId:352, povName:"Daenerys Targaryen",title:"Daenerys I"},
{id:86,bookId:1,chapterInBook:13, povId:851, povName:"Jon Snow",title:"Jon II"},
{id:87,bookId:1,chapterInBook:14, povId:136, povName:"Arya Stark",title:"Arya IV"},
{id:88,bookId:1,chapterInBook:15, povId:1716, povName:"Tyrion Lannister",title:"Tyrion III"},
{id:89,bookId:1,chapterInBook:16, povId:240, povName:"Bran Stark",title:"Bran II"},
{id:90,bookId:1,chapterInBook:17, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IV"},
{id:91,bookId:1,chapterInBook:18, povId:1530, povName:"Sansa Stark",title:"Sansa II"},
{id:92,bookId:1,chapterInBook:19, povId:136, povName:"Arya Stark",title:"Arya V"},
{id:93,bookId:1,chapterInBook:20, povId:1716, povName:"Tyrion Lannister",title:"Tyrion V"},
{id:94,bookId:1,chapterInBook:21, povId:240, povName:"Bran Stark",title:"Bran III"},
{id:95,bookId:1,chapterInBook:22, povId:287, povName:"Catelyn Tully",title:"Catelyn II"},
{id:96,bookId:1,chapterInBook:23, povId:851, povName:"Jon Snow",title:"Jon III"},
{id:97,bookId:1,chapterInBook:24, povId:1648, povName:"Theon Greyjoy",title:"Theon II"},
{id:98,bookId:1,chapterInBook:25, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VI"},
{id:99,bookId:1,chapterInBook:26, povId:136, povName:"Arya Stark",title:"Arya VI"},
{id:100,bookId:1,chapterInBook:27, povId:352, povName:"Daenerys Targaryen",title:"Daenerys II"},
{id:101,bookId:1,chapterInBook:28, povId:240, povName:"Bran Stark",title:"Bran IV"},
{id:102,bookId:1,chapterInBook:29, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VII"},
{id:103,bookId:1,chapterInBook:30, povId:136, povName:"Arya Stark",title:"Arya VII"},
{id:104,bookId:1,chapterInBook:31, povId:287, povName:"Catelyn Tully",title:"Catelyn III"},
{id:105,bookId:1,chapterInBook:32, povId:1530, povName:"Sansa Stark",title:"Sansa III"},
{id:106,bookId:1,chapterInBook:33, povId:287, povName:"Catelyn Tully",title:"Catelyn IV"},
{id:107,bookId:1,chapterInBook:34, povId:851, povName:"Jon Snow",title:"Jon IV"},
{id:108,bookId:1,chapterInBook:35, povId:240, povName:"Bran Stark",title:"Bran V"},
{id:109,bookId:1,chapterInBook:36, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VIII"},
{id:110,bookId:1,chapterInBook:37, povId:1648, povName:"Theon Greyjoy",title:"Theon III"},
{id:111,bookId:1,chapterInBook:38, povId:136, povName:"Arya Stark",title:"Arya VIII"},
{id:112,bookId:1,chapterInBook:39, povId:287, povName:"Catelyn Tully",title:"Catelyn V"},
{id:113,bookId:1,chapterInBook:40, povId:352, povName:"Daenerys Targaryen",title:"Daenerys III"},
{id:114,bookId:1,chapterInBook:41, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IX"},
{id:115,bookId:1,chapterInBook:42, povId:385, povName:"Davos Seaworth",title:"Davos II"},
{id:116,bookId:1,chapterInBook:43, povId:851, povName:"Jon Snow",title:"Jon V"},
{id:117,bookId:1,chapterInBook:44, povId:1716, povName:"Tyrion Lannister",title:"Tyrion X"},
{id:118,bookId:1,chapterInBook:45, povId:287, povName:"Catelyn Tully",title:"Catelyn VI"},
{id:119,bookId:1,chapterInBook:46, povId:240, povName:"Bran Stark",title:"Bran VI"},
{id:120,bookId:1,chapterInBook:47, povId:136, povName:"Arya Stark",title:"Arya IX"},
{id:121,bookId:1,chapterInBook:48, povId:352, povName:"Daenerys Targaryen",title:"Daenerys IV"},
{id:122,bookId:1,chapterInBook:49, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XI"},
{id:123,bookId:1,chapterInBook:50, povId:1648, povName:"Theon Greyjoy",title:"Theon IV"},
{id:124,bookId:1,chapterInBook:51, povId:851, povName:"Jon Snow",title:"Jon VI"},
{id:125,bookId:1,chapterInBook:52, povId:1530, povName:"Sansa Stark",title:"Sansa IV"},
{id:126,bookId:1,chapterInBook:53, povId:851, povName:"Jon Snow",title:"Jon VII"},
{id:127,bookId:1,chapterInBook:54, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XII"},
{id:128,bookId:1,chapterInBook:55, povId:287, povName:"Catelyn Tully",title:"Catelyn VII"},
{id:129,bookId:1,chapterInBook:56, povId:1648, povName:"Theon Greyjoy",title:"Theon V"},
{id:130,bookId:1,chapterInBook:57, povId:1530, povName:"Sansa Stark",title:"Sansa V"},
{id:131,bookId:1,chapterInBook:58, povId:385, povName:"Davos Seaworth",title:"Davos III"},
{id:132,bookId:1,chapterInBook:59, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XIII"},
{id:133,bookId:1,chapterInBook:60, povId:1530, povName:"Sansa Stark",title:"Sansa VI"},
{id:134,bookId:1,chapterInBook:61, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XIV"},
{id:135,bookId:1,chapterInBook:62, povId:1530, povName:"Sansa Stark",title:"Sansa VII"},
{id:136,bookId:1,chapterInBook:63, povId:352, povName:"Daenerys Targaryen",title:"Daenerys V"},
{id:137,bookId:1,chapterInBook:64, povId:136, povName:"Arya Stark",title:"Arya X"},
{id:138,bookId:1,chapterInBook:65, povId:1530, povName:"Sansa Stark",title:"Sansa VIII"},
{id:139,bookId:1,chapterInBook:66, povId:1648, povName:"Theon Greyjoy",title:"Theon VI"},
{id:140,bookId:1,chapterInBook:67, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XV"},
{id:141,bookId:1,chapterInBook:68, povId:851, povName:"Jon Snow",title:"Jon VIII"},
{id:142,bookId:1,chapterInBook:69, povId:240, povName:"Bran Stark",title:"Bran VII"},

{id:143,bookId:2,chapterInBook:0, povId:300, povName:"Chett",title:"Prologue"},
{id:144,bookId:2,chapterInBook:1, povId:785, povName:"Jaime Lannister",title:"Jaime I"},
{id:145,bookId:2,chapterInBook:2, povId:287, povName:"Catelyn Tully",title:"Catelyn I"},
{id:146,bookId:2,chapterInBook:3, povId:136, povName:"Arya Stark",title:"Arya I"},
{id:147,bookId:2,chapterInBook:4, povId:1716, povName:"Tyrion Lannister",title:"Tyrion I"},
{id:148,bookId:2,chapterInBook:5, povId:385, povName:"Davos Seaworth",title:"Davos I"},
{id:149,bookId:2,chapterInBook:6, povId:1530, povName:"Sansa Stark",title:"Sansa I"},
{id:150,bookId:2,chapterInBook:7, povId:851, povName:"Jon Snow",title:"Jon I"},
{id:151,bookId:2,chapterInBook:8, povId:352, povName:"Daenerys Targaryen",title:"Daenerys I"},
{id:152,bookId:2,chapterInBook:9, povId:240, povName:"Bran Stark",title:"Bran I"},
{id:153,bookId:2,chapterInBook:10, povId:385, povName:"Davos Seaworth",title:"Davos II"},
{id:154,bookId:2,chapterInBook:11, povId:785, povName:"Jaime Lannister",title:"Jaime II"},
{id:155,bookId:2,chapterInBook:12, povId:1716, povName:"Tyrion Lannister",title:"Tyrion II"},
{id:156,bookId:2,chapterInBook:13, povId:136, povName:"Arya Stark",title:"Arya II"},
{id:157,bookId:2,chapterInBook:14, povId:287, povName:"Catelyn Tully",title:"Catelyn II"},
{id:158,bookId:2,chapterInBook:15, povId:851, povName:"Jon Snow",title:"Jon II"},
{id:159,bookId:2,chapterInBook:16, povId:1530, povName:"Sansa Stark",title:"Sansa II"},
{id:160,bookId:2,chapterInBook:17, povId:136, povName:"Arya Stark",title:"Arya III"},
{id:161,bookId:2,chapterInBook:18, povId:1527, povName:"Samwell Tarly",title:"Samwell I"},
{id:162,bookId:2,chapterInBook:19, povId:1716, povName:"Tyrion Lannister",title:"Tyrion III"},
{id:163,bookId:2,chapterInBook:20, povId:287, povName:"Catelyn Tully",title:"Catelyn III"},
{id:164,bookId:2,chapterInBook:21, povId:785, povName:"Jaime Lannister",title:"Jaime III"},
{id:165,bookId:2,chapterInBook:22, povId:136, povName:"Arya Stark",title:"Arya IV"},
{id:166,bookId:2,chapterInBook:23, povId:352, povName:"Daenerys Targaryen",title:"Daenerys II"},
{id:167,bookId:2,chapterInBook:24, povId:240, povName:"Bran Stark",title:"Bran II"},
{id:168,bookId:2,chapterInBook:25, povId:385, povName:"Davos Seaworth",title:"Davos III"},
{id:169,bookId:2,chapterInBook:26, povId:851, povName:"Jon Snow",title:"Jon III"},
{id:170,bookId:2,chapterInBook:27, povId:352, povName:"Daenerys Targaryen",title:"Daenerys III"},
{id:171,bookId:2,chapterInBook:28, povId:1530, povName:"Sansa Stark",title:"Sansa III"},
{id:172,bookId:2,chapterInBook:29, povId:136, povName:"Arya Stark",title:"Arya V"},
{id:173,bookId:2,chapterInBook:30, povId:851, povName:"Jon Snow",title:"Jon IV"},
{id:174,bookId:2,chapterInBook:31, povId:785, povName:"Jaime Lannister",title:"Jaime IV"},
{id:175,bookId:2,chapterInBook:32, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IV"},
{id:176,bookId:2,chapterInBook:33, povId:1527, povName:"Samwell Tarly",title:"Samwell II"},
{id:177,bookId:2,chapterInBook:34, povId:136, povName:"Arya Stark",title:"Arya VI"},
{id:178,bookId:2,chapterInBook:35, povId:287, povName:"Catelyn Tully",title:"Catelyn IV"},
{id:179,bookId:2,chapterInBook:36, povId:385, povName:"Davos Seaworth",title:"Davos IV"},
{id:180,bookId:2,chapterInBook:37, povId:785, povName:"Jaime Lannister",title:"Jaime V"},
{id:181,bookId:2,chapterInBook:38, povId:1716, povName:"Tyrion Lannister",title:"Tyrion V"},
{id:182,bookId:2,chapterInBook:39, povId:136, povName:"Arya Stark",title:"Arya VII"},
{id:183,bookId:2,chapterInBook:40, povId:240, povName:"Bran Stark",title:"Bran III"},
{id:184,bookId:2,chapterInBook:41, povId:851, povName:"Jon Snow",title:"Jon V"},
{id:185,bookId:2,chapterInBook:42, povId:352, povName:"Daenerys Targaryen",title:"Daenerys IV"},
{id:186,bookId:2,chapterInBook:43, povId:136, povName:"Arya Stark",title:"Arya VIII"},
{id:187,bookId:2,chapterInBook:44, povId:785, povName:"Jaime Lannister",title:"Jaime VI"},
{id:188,bookId:2,chapterInBook:45, povId:287, povName:"Catelyn Tully",title:"Catelyn V"},
{id:189,bookId:2,chapterInBook:46, povId:1527, povName:"Samwell Tarly",title:"Samwell III"},
{id:190,bookId:2,chapterInBook:47, povId:136, povName:"Arya Stark",title:"Arya IX"},
{id:191,bookId:2,chapterInBook:48, povId:851, povName:"Jon Snow",title:"Jon VI"},
{id:192,bookId:2,chapterInBook:49, povId:287, povName:"Catelyn Tully",title:"Catelyn VI"},
{id:193,bookId:2,chapterInBook:50, povId:136, povName:"Arya Stark",title:"Arya X"},
{id:194,bookId:2,chapterInBook:51, povId:287, povName:"Catelyn Tully",title:"Catelyn VII"},
{id:195,bookId:2,chapterInBook:52, povId:136, povName:"Arya Stark",title:"Arya XI"},
{id:196,bookId:2,chapterInBook:53, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VI"},
{id:197,bookId:2,chapterInBook:54, povId:385, povName:"Davos Seaworth",title:"Davos V"},
{id:198,bookId:2,chapterInBook:55, povId:851, povName:"Jon Snow",title:"Jon VII"},
{id:199,bookId:2,chapterInBook:56, povId:240, povName:"Bran Stark",title:"Bran IV"},
{id:200,bookId:2,chapterInBook:57, povId:352, povName:"Daenerys Targaryen",title:"Daenerys V"},
{id:201,bookId:2,chapterInBook:58, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VII"},
{id:202,bookId:2,chapterInBook:59, povId:1530, povName:"Sansa Stark",title:"Sansa IV"},
{id:203,bookId:2,chapterInBook:60, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VIII"},
{id:204,bookId:2,chapterInBook:61, povId:1530, povName:"Sansa Stark",title:"Sansa V"},
{id:205,bookId:2,chapterInBook:62, povId:785, povName:"Jaime Lannister",title:"Jaime VII"},
{id:206,bookId:2,chapterInBook:63, povId:385, povName:"Davos Seaworth",title:"Davos VI"},
{id:207,bookId:2,chapterInBook:64, povId:851, povName:"Jon Snow",title:"Jon VIII"},
{id:208,bookId:2,chapterInBook:65, povId:136, povName:"Arya Stark",title:"Arya XII"},
{id:209,bookId:2,chapterInBook:66, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IX"},
{id:210,bookId:2,chapterInBook:67, povId:785, povName:"Jaime Lannister",title:"Jaime VIII"},
{id:211,bookId:2,chapterInBook:68, povId:1530, povName:"Sansa Stark",title:"Sansa VI"},
{id:212,bookId:2,chapterInBook:69, povId:851, povName:"Jon Snow",title:"Jon IX"},
{id:213,bookId:2,chapterInBook:70, povId:1716, povName:"Tyrion Lannister",title:"Tyrion X"},
{id:214,bookId:2,chapterInBook:71, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VI"},
{id:215,bookId:2,chapterInBook:72, povId:785, povName:"Jaime Lannister",title:"Jaime IX"},
{id:216,bookId:2,chapterInBook:73, povId:851, povName:"Jon Snow",title:"Jon X"},
{id:217,bookId:2,chapterInBook:74, povId:136, povName:"Arya Stark",title:"Arya XIII"},
{id:218,bookId:2,chapterInBook:75, povId:1527, povName:"Samwell Tarly",title:"Samwell IV"},
{id:219,bookId:2,chapterInBook:76, povId:851, povName:"Jon Snow",title:"Jon XI"},
{id:220,bookId:2,chapterInBook:77, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XI"},
{id:221,bookId:2,chapterInBook:78, povId:1527, povName:"Samwell Tarly",title:"Samwell V"},
{id:222,bookId:2,chapterInBook:79, povId:851, povName:"Jon Snow",title:"Jon XII"},
{id:223,bookId:2,chapterInBook:80, povId:1530, povName:"Sansa Stark",title:"Sansa VII"},
{id:224,bookId:2,chapterInBook:81, povId:1137, povName:"Merrett Frey",title:"Epilogue"},

{id:225,bookId:3,chapterInBook:0, povId:1286, povName:"Pate (Old)",title:"Prologue"},
{id:226,bookId:3,chapterInBook:1, povId:25, povName:"Aeron Greyjoy",title:"The Prophet"},
{id:227,bookId:3,chapterInBook:2, povId:110, povName:"Areo Hotah",title:"The Captain Of Guards"},
{id:228,bookId:3,chapterInBook:3, povId:295, povName:"Cersei Lannister",title:"Cersei I"},
{id:229,bookId:3,chapterInBook:4, povId:255, povName:"Brienne of Tarth",title:"Brienne I"},
{id:230,bookId:3,chapterInBook:5, povId:1527, povName:"Samwell Tarly",title:"Samwell I"},
{id:231,bookId:3,chapterInBook:6, povId:136, povName:"Arya Stark",title:"Arya I"},
{id:232,bookId:3,chapterInBook:7, povId:295, povName:"Cersei Lannister",title:"Cersei II"},
{id:233,bookId:3,chapterInBook:8, povId:785, povName:"Jaime Lannister",title:"Jaime I"},
{id:234,bookId:3,chapterInBook:9, povId:255, povName:"Brienne of Tarth",title:"Brienne II"},
{id:235,bookId:3,chapterInBook:10, povId:1530, povName:"Sansa Stark",title:"Sansa I"},
{id:236,bookId:3,chapterInBook:11, povId:138, povName:"Asha Greyjoy",title:"The Kraken's Daughter"},
{id:237,bookId:3,chapterInBook:12, povId:295, povName:"Cersei Lannister",title:"Cersei III"},
{id:238,bookId:3,chapterInBook:13, povId:137, povName:"Arys Oakheart",title:"The Soiled Knight"},
{id:239,bookId:3,chapterInBook:14, povId:255, povName:"Brienne of Tarth",title:"Brienne III"},
{id:240,bookId:3,chapterInBook:15, povId:1527, povName:"Samwell Tarly",title:"Samwell II"},
{id:241,bookId:3,chapterInBook:16, povId:785, povName:"Jaime Lannister",title:"Jaime II"},
{id:242,bookId:3,chapterInBook:17, povId:295, povName:"Cersei Lannister",title:"Cersei IV"},
{id:243,bookId:3,chapterInBook:18, povId:1763, povName:"Victarion Greyjoy",title:"The Iron Captain"},
{id:244,bookId:3,chapterInBook:19, povId:25, povName:"Aeron Greyjoy",title:"The Drowned Man"},
{id:245,bookId:3,chapterInBook:20, povId:255, povName:"Brienne of Tarth",title:"Brienne IV"},
{id:246,bookId:3,chapterInBook:21, povId:113, povName:"Arianne Martell",title:"The Queenmaker"},
{id:247,bookId:3,chapterInBook:22, povId:136, povName:"Arya Stark",title:"Arya II"},
{id:248,bookId:3,chapterInBook:23, povId:1530, povName:"Sansa Stark",title:"Alayne I"},
{id:249,bookId:3,chapterInBook:24, povId:295, povName:"Cersei Lannister",title:"Cersei V"},
{id:250,bookId:3,chapterInBook:25, povId:255, povName:"Brienne of Tarth",title:"Brienne V"},
{id:251,bookId:3,chapterInBook:26, povId:1527, povName:"Samwell Tarly",title:"Samwell III"},
{id:252,bookId:3,chapterInBook:27, povId:785, povName:"Jaime Lannister",title:"Jaime III"},
{id:253,bookId:3,chapterInBook:28, povId:295, povName:"Cersei Lannister",title:"Cersei VI"},
{id:254,bookId:3,chapterInBook:29, povId:1763, povName:"Victarion Greyjoy",title:"The Reaver"},
{id:255,bookId:3,chapterInBook:30, povId:785, povName:"Jaime Lannister",title:"Jaime IV"},
{id:256,bookId:3,chapterInBook:31, povId:255, povName:"Brienne of Tarth",title:"Brienne VI"},
{id:257,bookId:3,chapterInBook:32, povId:295, povName:"Cersei Lannister",title:"Cersei VII"},
{id:258,bookId:3,chapterInBook:33, povId:785, povName:"Jaime Lannister",title:"Jaime V"},
{id:259,bookId:3,chapterInBook:34, povId:136, povName:"Arya Stark",title:"Cat Of The Canals"},
{id:260,bookId:3,chapterInBook:35, povId:1527, povName:"Samwell Tarly",title:"Samwell IV"},
{id:261,bookId:3,chapterInBook:36, povId:295, povName:"Cersei Lannister",title:"Cersei VIII"},
{id:262,bookId:3,chapterInBook:37, povId:255, povName:"Brienne of Tarth",title:"Brienne VII"},
{id:263,bookId:3,chapterInBook:38, povId:785, povName:"Jaime Lannister",title:"Jaime VI"},
{id:264,bookId:3,chapterInBook:39, povId:295, povName:"Cersei Lannister",title:"Cersei IX"},
{id:265,bookId:3,chapterInBook:40, povId:113, povName:"Arianne Martell",title:"The Princess In The Tower"},
{id:266,bookId:3,chapterInBook:41, povId:1530, povName:"Sansa Stark",title:"Alayne II"},
{id:267,bookId:3,chapterInBook:42, povId:255, povName:"Brienne of Tarth",title:"Brienne VIII"},
{id:268,bookId:3,chapterInBook:43, povId:295, povName:"Cersei Lannister",title:"Cersei X"},
{id:269,bookId:3,chapterInBook:44, povId:785, povName:"Jaime Lannister",title:"Jaime VII"},
{id:270,bookId:3,chapterInBook:45, povId:1527, povName:"Samwell Tarly",title:"Samwell V"},

{id:271,bookId:4,chapterInBook:0, povId:1753, povName:"Varamyr",title:"Prologue"},
{id:272,bookId:4,chapterInBook:1, povId:1716, povName:"Tyrion Lannister",title:"Tyrion I"},
{id:273,bookId:4,chapterInBook:2, povId:352, povName:"Daenerys Targaryen",title:"Daenerys I"},
{id:274,bookId:4,chapterInBook:3, povId:851, povName:"Jon Snow",title:"Jon I"},
{id:275,bookId:4,chapterInBook:4, povId:240, povName:"Bran Stark",title:"Bran I"},
{id:276,bookId:4,chapterInBook:5, povId:1716, povName:"Tyrion Lannister",title:"Tyrion II"},
{id:277,bookId:4,chapterInBook:6, povId:1351, povName:"Quentyn Martell",title:"The Merchant's Man"},
{id:278,bookId:4,chapterInBook:7, povId:851, povName:"Jon Snow",title:"Jon II"},
{id:279,bookId:4,chapterInBook:8, povId:1716, povName:"Tyrion Lannister",title:"Tyrion III"},
{id:280,bookId:4,chapterInBook:9, povId:385, povName:"Davos Seaworth",title:"Davos I"},
{id:281,bookId:4,chapterInBook:10, povId:851, povName:"Jon Snow",title:"Jon III"},
{id:282,bookId:4,chapterInBook:11, povId:352, povName:"Daenerys Targaryen",title:"Daenerys II"},
{id:283,bookId:4,chapterInBook:12, povId:1648, povName:"Theon Greyjoy",title:"Reek I"},
{id:284,bookId:4,chapterInBook:13, povId:240, povName:"Bran Stark",title:"Bran II"},
{id:285,bookId:4,chapterInBook:14, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IV"},
{id:286,bookId:4,chapterInBook:15, povId:385, povName:"Davos Seaworth",title:"Davos II"},
{id:287,bookId:4,chapterInBook:16, povId:352, povName:"Daenerys Targaryen",title:"Daenerys III"},
{id:288,bookId:4,chapterInBook:17, povId:851, povName:"Jon Snow",title:"Jon IV"},
{id:289,bookId:4,chapterInBook:18, povId:1716, povName:"Tyrion Lannister",title:"Tyrion V"},
{id:290,bookId:4,chapterInBook:19, povId:385, povName:"Davos Seaworth",title:"Davos III"},
{id:291,bookId:4,chapterInBook:20, povId:1648, povName:"Theon Greyjoy",title:"Reek II"},
{id:292,bookId:4,chapterInBook:21, povId:851, povName:"Jon Snow",title:"Jon V"},
{id:293,bookId:4,chapterInBook:22, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VI"},
{id:294,bookId:4,chapterInBook:23, povId:352, povName:"Daenerys Targaryen",title:"Daenerys IV"},
{id:295,bookId:4,chapterInBook:24, povId:840, povName:"Jon Connington",title:"The Lost Lord"},
{id:296,bookId:4,chapterInBook:25, povId:1351, povName:"Quentyn Martell",title:"The Windblown"},
{id:297,bookId:4,chapterInBook:26, povId:138, povName:"Asha Greyjoy",title:"The Wayward Bride"},
{id:298,bookId:4,chapterInBook:27, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VII"},
{id:299,bookId:4,chapterInBook:28, povId:851, povName:"Jon Snow",title:"Jon VI"},
{id:300,bookId:4,chapterInBook:29, povId:385, povName:"Davos Seaworth",title:"Davos IV"},
{id:301,bookId:4,chapterInBook:30, povId:352, povName:"Daenerys Targaryen",title:"Daenerys V"},
{id:302,bookId:4,chapterInBook:31, povId:1122, povName:"Melisandre",title:"Melisandre I"},
{id:303,bookId:4,chapterInBook:32, povId:1648, povName:"Theon Greyjoy",title:"Reek III"},
{id:304,bookId:4,chapterInBook:33, povId:1716, povName:"Tyrion Lannister",title:"Tyrion VIII"},
{id:305,bookId:4,chapterInBook:34, povId:240, povName:"Bran Stark",title:"Bran III"},
{id:306,bookId:4,chapterInBook:35, povId:851, povName:"Jon Snow",title:"Jon VII"},
{id:307,bookId:4,chapterInBook:36, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VI"},
{id:308,bookId:4,chapterInBook:37, povId:1648, povName:"Theon Greyjoy",title:"The Prince of Winterfell"},
{id:309,bookId:4,chapterInBook:38, povId:110, povName:"Areo Hotah",title:"The Watcher"},
{id:310,bookId:4,chapterInBook:39, povId:851, povName:"Jon Snow",title:"Jon VIII"},
{id:311,bookId:4,chapterInBook:40, povId:1716, povName:"Tyrion Lannister",title:"Tyrion IX"},
{id:312,bookId:4,chapterInBook:41, povId:1648, povName:"Theon Greyjoy",title:"The Turncloak"},
{id:313,bookId:4,chapterInBook:42, povId:138, povName:"Asha Greyjoy",title:"The King's Prize"},
{id:314,bookId:4,chapterInBook:43, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VII"},
{id:315,bookId:4,chapterInBook:44, povId:851, povName:"Jon Snow",title:"Jon IX"},
{id:316,bookId:4,chapterInBook:45, povId:136, povName:"Arya Stark",title:"The Blind Girl"},
{id:317,bookId:4,chapterInBook:46, povId:1648, povName:"Theon Greyjoy",title:"A Ghost in Winterfell"},
{id:318,bookId:4,chapterInBook:47, povId:1716, povName:"Tyrion Lannister",title:"Tyrion X"},
{id:319,bookId:4,chapterInBook:48, povId:785, povName:"Jaime Lannister",title:"Jaime I"},
{id:320,bookId:4,chapterInBook:49, povId:851, povName:"Jon Snow",title:"Jon X"},
{id:321,bookId:4,chapterInBook:50, povId:352, povName:"Daenerys Targaryen",title:"Daenerys VIII"},
{id:322,bookId:4,chapterInBook:51, povId:1648, povName:"Theon Greyjoy",title:"Theon I"},
{id:323,bookId:4,chapterInBook:52, povId:352, povName:"Daenerys Targaryen",title:"Daenerys IX"},
{id:324,bookId:4,chapterInBook:53, povId:851, povName:"Jon Snow",title:"Jon XI"},
{id:325,bookId:4,chapterInBook:54, povId:295, povName:"Cersei Lannister",title:"Cersei I"},
{id:326,bookId:4,chapterInBook:55, povId:163, povName:"Barristan Selmy",title:"The Queensguard"},
{id:327,bookId:4,chapterInBook:56, povId:1763, povName:"Victarion Greyjoy",title:"The Iron Suitor"},
{id:328,bookId:4,chapterInBook:57, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XI"},
{id:329,bookId:4,chapterInBook:58, povId:851, povName:"Jon Snow",title:"Jon XII"},
{id:330,bookId:4,chapterInBook:59, povId:163, povName:"Barristan Selmy",title:"The Discarded Knight"},
{id:331,bookId:4,chapterInBook:60, povId:1351, povName:"Quentyn Martell",title:"The Spurned Suitor"},
{id:332,bookId:4,chapterInBook:61, povId:840, povName:"Jon Connington",title:"The Griffin Reborn"},
{id:333,bookId:4,chapterInBook:62, povId:138, povName:"Asha Greyjoy",title:"The Sacrifice"},
{id:334,bookId:4,chapterInBook:63, povId:1763, povName:"Victarion Greyjoy",title:"Victarion I"},
{id:335,bookId:4,chapterInBook:64, povId:136, povName:"Arya Stark",title:"The Ugly Little Girl"},
{id:336,bookId:4,chapterInBook:65, povId:295, povName:"Cersei Lannister",title:"Cersei II"},
{id:337,bookId:4,chapterInBook:66, povId:1716, povName:"Tyrion Lannister",title:"Tyrion XII"},
{id:338,bookId:4,chapterInBook:67, povId:163, povName:"Barristan Selmy",title:"The Kingbreaker"},
{id:339,bookId:4,chapterInBook:68, povId:1351, povName:"Quentyn Martell",title:"The Dragontamer"},
{id:340,bookId:4,chapterInBook:69, povId:851, povName:"Jon Snow",title:"Jon XIII"},
{id:341,bookId:4,chapterInBook:70, povId:163, povName:"Barristan Selmy",title:"The Queen's Hand"},
{id:342,bookId:4,chapterInBook:71, povId:352, povName:"Daenerys Targaryen",title:"Daenerys X"},
{id:343,bookId:4,chapterInBook:72, povId:900, povName:"Kevan Lannister",title:"Epilogue"}
];

var travels=[
{chapterId:0,title:"Prologue", source:"Castle Black", target:"deserted wildling village", mode:0},
{chapterId:1,title:"Bran I", source:"Winterfell", target:"Wolfswood", mode:0},
{chapterId:2,title:"Catelyn I", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:3,title:"Daenerys I", source:"Pentos", target:"Khal Drogo's manse", mode:0},
{chapterId:4,title:"Eddard I", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:5,title:"Jon I", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:6,title:"Catelyn II", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:7,title:"Arya I", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:8,title:"Bran II", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:9,title:"Tyrion I", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:10,title:"Jon II", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:11,title:"Daenerys II", source:"Khal Drogo's manse", target:"field outside of Pentos", mode:0},
{chapterId:12,title:"Eddard II", source:"Winterfell", target:"kingsroad, south of Winterfell", mode:0},
{chapterId:13,title:"Tyrion II", source:"Winterfell", target:"kingsroad, north of Winterfell", mode:0},
{chapterId:14,title:"Catelyn III", source:"Winterfell", target:"White Harbor", mode:0},
{chapterId:15,title:"Sansa I", source:"kingsroad, north of Winterfell", target:"camp near the Trident", mode:0},
{chapterId:16,title:"Eddard III", source:"camp near the Trident", target:"Castle Darry", mode:0},
{chapterId:17,title:"Bran III", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:18,title:"Catelyn IV", source:"White Harbor", target:"King's Landing", mode:1},
{chapterId:19,title:"Jon III", source:"kingsroad, north of Winterfell", target:"Castle Black", mode:0},
{chapterId:20,title:"Eddard IV", source:"Castle Darry", target:"King's Landing", mode:0},
{chapterId:21,title:"Tyrion III", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:22,title:"Arya II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:23,title:"Daenerys III", source:"field outside of Pentos", target:"Dothraki Sea", mode:0},
{chapterId:24,title:"Bran IV", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:25,title:"Eddard V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:26,title:"Jon IV", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:27,title:"Eddard VI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:28,title:"Catelyn V", source:"White Harbor", target:"Old Crossroads Inn", mode:0},
{chapterId:29,title:"Sansa II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:30,title:"Eddard VII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:31,title:"Tyrion IV", source:"Old Crossroads Inn", target:"Mountains of the Moon", mode:0},
{chapterId:32,title:"Arya III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:33,title:"Eddard VIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:34,title:"Catelyn VI", source:"Mountains of the Moon", target:"the Eyrie", mode:0},
{chapterId:35,title:"Eddard IX", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:36,title:"Daenerys IV", source:"Dothraki Sea", target:"Vaes Dothrak", mode:0},
{chapterId:37,title:"Bran V", source:"Winterfell", target:"Wolfswood", mode:0},
{chapterId:38,title:"Tyrion V", source:"the Eyrie", target:"the Eyrie", mode:0},
{chapterId:39,title:"Eddard X", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:40,title:"Catelyn VII", source:"the Eyrie", target:"High Road (near the Eyrie)", mode:0},
{chapterId:41,title:"Jon V", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:42,title:"Tyrion VI", source:"High Road (near the Eyrie)", target:"High Road (in Mountains of the Moon)", mode:0},
{chapterId:43,title:"Eddard XI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:44,title:"Sansa III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:45,title:"Eddard XII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:46,title:"Daenerys V", source:"Vaes Dothrak", target:"Vaes Dothrak", mode:0},
{chapterId:47,title:"Eddard XIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:48,title:"Jon VI", source:"Castle Black", target:"Weirwood north of the Wall", mode:0},
{chapterId:49,title:"Eddard XIV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:50,title:"Arya IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:51,title:"Sansa IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:52,title:"Jon VII", source:"Weirwood north of the Wall", target:"Castle Black", mode:0},
{chapterId:53,title:"Bran VI", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:54,title:"Daenerys VI", source:"Vaes Dothrak", target:"Vaes Dothrak", mode:0},
{chapterId:55,title:"Catelyn VIII", source:"Winterfell", target:"Moat Cailin", mode:0},
{chapterId:56,title:"Tyrion VII", source:"High Road (in Mountains of the Moon)", target:"Old Crossroads Inn", mode:0},
{chapterId:57,title:"Sansa V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:58,title:"Eddard XV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:59,title:"Catelyn IX", source:"Moat Cailin", target:"the Twins", mode:0},
{chapterId:60,title:"Jon VIII", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:61,title:"Daenerys VII", source:"Vaes Dothrak", target:"Lhazareen village", mode:0},
{chapterId:62,title:"Tyrion VIII", source:"Old Crossroads Inn", target:"Green Fork", mode:0},
{chapterId:63,title:"Catelyn X", source:"the Twins", target:"Whispering Wood", mode:0},
{chapterId:64,title:"Daenerys VIII", source:"Lhazareen village", target:"Red Waste", mode:0},
{chapterId:65,title:"Arya V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:66,title:"Bran VII", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:67,title:"Sansa VI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:68,title:"Daenerys IX", source:"Red Waste", target:"Red Waste", mode:0},
{chapterId:69,title:"Tyrion IX", source:"Green Fork", target:"Green Fork", mode:0},
{chapterId:70,title:"Jon IX", source:"Castle Black", target:"Mole's Town", mode:0},
{chapterId:70,title:"Jon IX", source:"Mole's Town", target:"Castle Black", mode:0},
{chapterId:71,title:"Catelyn XI", source:"Whispering Wood", target:"Riverrun", mode:0},
{chapterId:72,title:"Daenerys X", source:"Red Waste", target:"Red Waste", mode:0},
{chapterId:73,title:"Prologue", source:"Dragonstone", target:"Dragonstone", mode:0},
{chapterId:74,title:"Arya I", source:"King's Landing", target:"Kingsroad, a little north of King's Landing", mode:0},
{chapterId:75,title:"Sansa I", source:"Green Fork", target:"King's Landing", mode:0},
{chapterId:76,title:"Tyrion I", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:77,title:"Bran I", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:78,title:"Arya II", source:"Kingsroad, a little north of King's Landing", target:"Inn south of the God's eye", mode:0},
{chapterId:79,title:"Jon I", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:80,title:"Catelyn I", source:"Riverrun", target:"Seagard", mode:0},
{chapterId:81,title:"Tyrion II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:82,title:"Arya III", source:"Inn south of the God's eye", target:"Holdfast on west shore of God's eye", mode:0},
{chapterId:83,title:"Davos I", source:"Dragonstone", target:"Storm's end", mode:1},
{chapterId:84,title:"Theon I", source:"Seagard", target:"Lordsport", mode:1},
{chapterId:85,title:"Daenerys I", source:"Red Waste", target:"Vaes Tolorro", mode:0},
{chapterId:86,title:"Jon II", source:"Castle Black", target:"Whitetree", mode:0},
{chapterId:87,title:"Arya IV", source:"Holdfast on west shore of God's eye", target:"Holdfast on west shore of God's eye", mode:0},
{chapterId:88,title:"Tyrion III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:89,title:"Bran II", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:90,title:"Tyrion IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:91,title:"Sansa II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:92,title:"Arya V", source:"Holdfast on west shore of God's eye", target:"Fishing village east of God's eye", mode:0},
{chapterId:93,title:"Tyrion V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:94,title:"Bran III", source:"Greywater Watch", target:"Winterfell", mode:0},
{chapterId:95,title:"Catelyn II", source:"Riverrun", target:"Bitterbridge", mode:0},
{chapterId:96,title:"Jon III", source:"Whitetree", target:"Craster's Keep", mode:0},
{chapterId:97,title:"Theon II", source:"Lordsport", target:"Pyke", mode:0},
{chapterId:98,title:"Tyrion VI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:99,title:"Arya VI", source:"Fishing village east of God's eye", target:"Harrenhal", mode:0},
{chapterId:100,title:"Daenerys II", source:"Vaes Tolorro", target:"Qarth", mode:0},
{chapterId:101,title:"Bran IV", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:102,title:"Tyrion VII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:103,title:"Arya VII", source:"Harrenhal", target:"Harrenhal", mode:0},
{chapterId:104,title:"Catelyn III", source:"Bitterbridge", target:"Storm's end", mode:0},
{chapterId:105,title:"Sansa III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:106,title:"Catelyn IV", source:"Storm's end", target:"Bitterbridge", mode:0},
{chapterId:107,title:"Jon IV", source:"Craster's Keep", target:"Fist of the First Men", mode:0},
{chapterId:108,title:"Bran V", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:109,title:"Tyrion VIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:110,title:"Theon III", source:"Pyke", target:"Stony Shore", mode:0},
{chapterId:110,title:"Theon III", source:"Stony Shore", target:"Torrhen's Square", mode:0},
{chapterId:111,title:"Arya VIII", source:"Harrenhal", target:"Harrenhal", mode:0},
{chapterId:112,title:"Catelyn V", source:"Bitterbridge", target:"Riverrun", mode:0},
{chapterId:113,title:"Daenerys III", source:"Qarth", target:"Qarth", mode:0},
{chapterId:114,title:"Tyrion IX", source:"King's Landing", target:"Dorne", mode:0},
{chapterId:115,title:"Davos II", source:"Storm's end", target:"Storm's end", mode:0},
{chapterId:116,title:"Jon V", source:"Shadow Tower", target:"Fist of the First Men", mode:0},
{chapterId:116,title:"Jon V", source:"Fist of the First Men", target:"Skirling pass", mode:0},
{chapterId:116,title:"Jon V", source:"Fist of the First Men", target:"Giant's stairs", mode:0},
{chapterId:116,title:"Jon V", source:"Fist of the First Men", target:"Milkwater", mode:0},
{chapterId:117,title:"Tyrion X", source:"King's Landing", target:"Castle Rosby", mode:0},
{chapterId:118,title:"Catelyn VI", source:"Riverrun", target:"Stone Mill", mode:0},
{chapterId:119,title:"Bran VI", source:"Stony Shore", target:"Winterfell", mode:0},
{chapterId:120,title:"Arya IX", source:"Harrenhal", target:"Harrenhal", mode:0},
{chapterId:121,title:"Daenerys IV", source:"Qarth", target:"Qarth", mode:0},
{chapterId:122,title:"Tyrion XI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:123,title:"Theon IV", source:"Winterfell", target:"Deepwood Motte", mode:0},
{chapterId:123,title:"Theon IV", source:"Winterfell", target:"Wolfswood", mode:0},
{chapterId:123,title:"Theon IV", source:"Wolfswood", target:"Mill on Acorn Water", mode:0},
{chapterId:124,title:"Jon VI", source:"Skirling pass", target:"Wilding ambush site", mode:0},
{chapterId:125,title:"Sansa IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:126,title:"Jon VII", source:"Wilding ambush site", target:"Skirling pass", mode:0},
{chapterId:127,title:"Tyrion XII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:128,title:"Catelyn VII", source:"Riverrun", target:"Riverrun", mode:0},
{chapterId:129,title:"Theon V", source:"Moat Cailin", target:"Winterfell", mode:0},
{chapterId:130,title:"Sansa V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:131,title:"Davos III", source:"Storm's end", target:"Blackwater Bay", mode:1},
{chapterId:132,title:"Tyrion XIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:133,title:"Sansa VI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:134,title:"Tyrion XIV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:135,title:"Sansa VII", source:"King's Landing", target:"Blackwater Bay", mode:0},
{chapterId:136,title:"Daenerys V", source:"Qarth", target:"Qarth", mode:0},
{chapterId:137,title:"Arya X", source:"Harrenhal", target:"outside of Harrenhal", mode:0},
{chapterId:137,title:"Arya X", source:"Castle Darry", target:"Duskendale", mode:0},
{chapterId:138,title:"Sansa VIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:139,title:"Theon VI", source:"Dreadfort", target:"Winterfell", mode:0},
{chapterId:140,title:"Tyrion XV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:141,title:"Jon VIII", source:"Skirling pass", target:"Skirling pass", mode:0},
{chapterId:142,title:"Bran VII", source:"Winterfell", target:"Wolfswood", mode:0},
{chapterId:143,title:"Prologue", source:"Fist of the First Men", target:"Fist of the First Men", mode:0},
{chapterId:144,title:"Jaime I", source:"Riverrun", target:"Red Fork", mode:0},
{chapterId:145,title:"Catelyn I", source:"Riverrun", target:"Riverrun", mode:0},
{chapterId:146,title:"Arya I", source:"outside of Harrenhal", target:"North of Harrenhal", mode:0},
{chapterId:147,title:"Tyrion I", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:148,title:"Davos I", source:"Blackwater Bay", target:"Dragonstone", mode:1},
{chapterId:149,title:"Sansa I", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:150,title:"Jon I", source:"Skirling pass", target:"Frostfangs", mode:0},
{chapterId:151,title:"Daenerys I", source:"Qarth", target:"Astapor", mode:1},
{chapterId:152,title:"Bran I", source:"Wolfswood", target:"Tumbledown tower", mode:0},
{chapterId:153,title:"Davos II", source:"Dragonstone", target:"Dragonstone", mode:0},
{chapterId:154,title:"Jaime II", source:"Red Fork", target:"Inn of the Kneeling Man", mode:0},
{chapterId:155,title:"Tyrion II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:156,title:"Arya II", source:"North of Harrenhal", target:"Inn of the Kneeling Man", mode:0},
{chapterId:157,title:"Catelyn II", source:"The Crag", target:"Riverrun", mode:0},
{chapterId:158,title:"Jon II", source:"Frostfangs", target:"Fist of the First Men", mode:0},
{chapterId:159,title:"Sansa II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:160,title:"Arya III", source:"Inn of the Kneeling Man", target:"Village that rests in the trees", mode:0},
{chapterId:161,title:"Samwell I", source:"Fist of the First Men", target:"Craster's Keep", mode:0},
{chapterId:162,title:"Tyrion III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:163,title:"Catelyn III", source:"Riverrun", target:"Riverrun", mode:0},
{chapterId:164,title:"Jaime III", source:"Inn of the Kneeling Man", target:"Encounter with the Brave Companions", mode:0},
{chapterId:165,title:"Arya IV", source:"Village that rests in the trees", target:"High Heart", mode:0},
{chapterId:165,title:"Arya IV", source:"High Heart", target:"Acorn Hall", mode:0},
{chapterId:166,title:"Daenerys II", source:"Astapor", target:"Astapor", mode:0},
{chapterId:167,title:"Bran II", source:"North of Tumbledown tower", target:"North of Tumbledown tower", mode:0},
{chapterId:168,title:"Davos III", source:"Dragonstone", target:"Dragonstone", mode:0},
{chapterId:169,title:"Jon III", source:"Fist of the First Men", target:"cavern in haunted forest", mode:0},
{chapterId:170,title:"Daenerys III", source:"Astapor", target:"Astapor", mode:0},
{chapterId:171,title:"Sansa III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:172,title:"Arya V", source:"Acorn Hall", target:"Stoney Sept", mode:0},
{chapterId:172,title:"Arya V", source:"Stoney Sept", target:"The Peach Inn", mode:0},
{chapterId:173,title:"Jon IV", source:"Haunted Forest", target:"The Wall, spot of first invasion", mode:0},
{chapterId:174,title:"Jaime IV", source:"Encounter with the Brave Companions", target:"Harrenhal", mode:0},
{chapterId:175,title:"Tyrion IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:176,title:"Samwell II", source:"Craster's Keep", target:"south of Craster's Keep", mode:0},
{chapterId:177,title:"Arya VI", source:"The Peach Inn", target:"Cave of Beric Dondarrion", mode:0},
{chapterId:178,title:"Catelyn IV", source:"Riverrun", target:"Riverrun", mode:0},
{chapterId:179,title:"Davos IV", source:"Dragonstone", target:"Dragonstone", mode:0},
{chapterId:180,title:"Jaime V", source:"Harrenhal", target:"Harrenhal", mode:0},
{chapterId:181,title:"Tyrion V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:182,title:"Arya VII", source:"Cave of Beric Dondarrion", target:"Town held by Bloody Mummers", mode:0},
{chapterId:183,title:"Bran III", source:"North of Tumbledown tower", target:"Queenscrown", mode:0},
{chapterId:184,title:"Jon V", source:"The Wall, spot of first invasion", target:"Queenscrown", mode:0},
{chapterId:185,title:"Daenerys IV", source:"Astapor", target:"Yunkai", mode:0},
{chapterId:186,title:"Arya VIII", source:"Town held by Bloody Mummers", target:"High Heart", mode:0},
{chapterId:186,title:"Arya VIII", source:"High Heart", target:"Village of lord Goodbrook", mode:0},
{chapterId:187,title:"Jaime VI", source:"Harrenhal", target:"Harrenhal", mode:0},
{chapterId:188,title:"Catelyn V", source:"Riverrun", target:"Oldstones", mode:0},
{chapterId:189,title:"Samwell III", source:"south of Craster's Keep", target:"abandonned Wilding Village", mode:0},
{chapterId:190,title:"Arya IX", source:"Village that rests in the trees", target:"Trident ferry", mode:0},
{chapterId:191,title:"Jon VI", source:"Queenscrown", target:"Castle Black", mode:0},
{chapterId:192,title:"Catelyn VI", source:"Oldstones", target:"camp around the Twins", mode:0},
{chapterId:193,title:"Arya X", source:"Trident ferry", target:"camp around the Twins", mode:0},
{chapterId:194,title:"Catelyn VII", source:"camp around the Twins", target:"the Twins", mode:0},
{chapterId:195,title:"Arya XI", source:"camp around the Twins", target:"camp around the Twins", mode:0},
{chapterId:196,title:"Tyrion VI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:197,title:"Davos V", source:"Dragonstone", target:"Dragonstone", mode:0},
{chapterId:198,title:"Jon VII", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:199,title:"Bran IV", source:"Queenscrown", target:"Nightfort", mode:0},
{chapterId:200,title:"Daenerys V", source:"Yunkai", target:"Meereen", mode:0},
{chapterId:201,title:"Tyrion VII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:202,title:"Sansa IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:203,title:"Tyrion VIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:204,title:"Sansa V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:205,title:"Jaime VII", source:"Harrenhal", target:"King's Landing", mode:0},
{chapterId:206,title:"Davos VI", source:"Dragonstone", target:"Lys", mode:1},
{chapterId:206,title:"Davos VI", source:"Dragonstone", target:"Eastwatch", mode:1},
{chapterId:207,title:"Jon VIII", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:208,title:"Arya XII", source:"camp around the Twins", target:"Old Crossroads Inn", mode:0},
{chapterId:209,title:"Tyrion IX", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:210,title:"Jaime VIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:211,title:"Sansa VI", source:"King's Landing", target:"Little Finger", mode:1},
{chapterId:212,title:"Jon IX", source:"Eastwatch", target:"Castle Black", mode:0},
{chapterId:213,title:"Tyrion X", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:214,title:"Daenerys VI", source:"Meereen", target:"Meereen", mode:0},
{chapterId:215,title:"Jaime IX", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:216,title:"Jon X", source:"Eastwatch", target:"Castle Black", mode:0},
{chapterId:217,title:"Arya XIII", source:"Old Crossroads Inn", target:"Saltpans", mode:0},
{chapterId:218,title:"Samwell IV", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:219,title:"Jon XI", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:220,title:"Tyrion XI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:221,title:"Samwell V", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:222,title:"Jon XII", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:223,title:"Sansa VII", source:"Little Finger", target:"the Eyrie", mode:0},
{chapterId:224,title:"Epilogue", source:"the Twins", target:"Oldstones", mode:0},
{chapterId:225,title:"Prologue", source:"Oldtown", target:"Oldtown", mode:0},
{chapterId:226,title:"The Prophet", source:"Hammerhorn", target:"Pebbleton", mode:0},
{chapterId:227,title:"The Captain Of Guards", source:"Water gardens", target:"Sunspear", mode:0},
{chapterId:228,title:"Cersei I", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:229,title:"Brienne I", source:"King's Landing", target:"Castle Rosby", mode:0},
{chapterId:230,title:"Samwell I", source:"Castle Black", target:"Eastwatch", mode:0},
{chapterId:231,title:"Arya I", source:"Saltpans", target:"Braavos", mode:1},
{chapterId:232,title:"Cersei II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:233,title:"Jaime I", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:234,title:"Brienne II", source:"Castle Rosby", target:"Duskendale", mode:0},
{chapterId:235,title:"Sansa I", source:"the Eyrie", target:"the Eyrie", mode:0},
{chapterId:236,title:"The Kraken's Daughter", source:"Deepwood Motte", target:"Ten Towers", mode:1},
{chapterId:237,title:"Cersei III", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:238,title:"The Soiled Knight", source:"Sunspear", target:"Sunspear", mode:0},
{chapterId:239,title:"Brienne III", source:"Duskendale", target:"Maidenpool", mode:0},
{chapterId:240,title:"Samwell II", source:"Eastwatch", target:"Braavos", mode:1},
{chapterId:241,title:"Jaime II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:242,title:"Cersei IV", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:243,title:"The Iron Captain", source:"West of the Iron Islands", target:"Old Wyk", mode:1},
{chapterId:244,title:"The Drowned Man", source:"Ten Towers", target:"Nagga's Hills", mode:1},
{chapterId:244,title:"The Drowned Man", source:"Old Wyk", target:"Nagga's Hills", mode:1},
{chapterId:244,title:"The Drowned Man", source:"Pebbleton", target:"Nagga's Hills", mode:1},
{chapterId:245,title:"Brienne IV", source:"Maidenpool", target:"the Whispers", mode:0},
{chapterId:246,title:"The Queenmaker", source:"Sunspear", target:"the Greenblood", mode:0},
{chapterId:247,title:"Arya II", source:"Braavos", target:"Braavos", mode:0},
{chapterId:248,title:"Alayne I", source:"the Eyrie", target:"the Eyrie", mode:0},
{chapterId:249,title:"Cersei V", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:250,title:"Brienne V", source:"the Whispers", target:"Maidenpool", mode:0},
{chapterId:250,title:"Brienne V", source:"Maidenpool", target:"Quiet Isle", mode:0},
{chapterId:251,title:"Samwell III", source:"Braavos", target:"Braavos", mode:0},
{chapterId:252,title:"Jaime III", source:"King's Landing", target:"Castle Hayford", mode:0},
{chapterId:253,title:"Cersei VI", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:254,title:"The Reaver", source:"Nagga's Hills", target:"Shield Islands", mode:1},
{chapterId:255,title:"Jaime IV", source:"Castle Hayford", target:"Castle Darry", mode:0},
{chapterId:256,title:"Brienne VI", source:"Quiet Isle", target:"Quiet Isle", mode:0},
{chapterId:257,title:"Cersei VII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:258,title:"Jaime V", source:"Castle Darry", target:"Riverrun", mode:0},
{chapterId:259,title:"Cat Of The Canals", source:"Braavos", target:"Braavos", mode:0},
{chapterId:260,title:"Samwell IV", source:"Braavos", target:"off the coast of Dorne", mode:1},
{chapterId:261,title:"Cersei VIII", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:262,title:"Brienne VII", source:"Quiet Isle", target:"Old Crossroads Inn", mode:0},
{chapterId:263,title:"Jaime VI", source:"Riverrun", target:"Riverrun", mode:0},
{chapterId:264,title:"Cersei IX", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:265,title:"The Princess In The Tower", source:"Sunspear", target:"Volantis", mode:1},
{chapterId:265,title:"The Princess In The Tower", source:"Sunspear", target:"Greenstone", mode:1},
{chapterId:265,title:"The Princess In The Tower", source:"Sunspear", target:"Norvos", mode:1},
{chapterId:265,title:"The Princess In The Tower", source:"Sunspear", target:"Tyrosh", mode:1},
{chapterId:266,title:"Alayne II", source:"the Eyrie", target:"Gates of the Moon", mode:0},
{chapterId:267,title:"Brienne VIII", source:"Old Crossroads Inn", target:"Cave of Beric Dondarrion", mode:0},
{chapterId:268,title:"Cersei X", source:"King's Landing", target:"Longtable", mode:0},
{chapterId:269,title:"Jaime VII", source:"Riverrun", target:"Riverrun", mode:0},
{chapterId:270,title:"Samwell V", source:"off the coast of Dorne", target:"Oldtown", mode:1},
{chapterId:271,title:"Prologue", source:"Castle Black", target:"abandonned Wilding Village", mode:0},
{chapterId:272,title:"Tyrion I", source:"King's Landing", target:"Pentos", mode:1},
{chapterId:273,title:"Daenerys I", source:"Meereen", target:"Meereen", mode:0},
{chapterId:274,title:"Jon I", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:275,title:"Bran I", source:"Nightfort", target:"Haunted Forest", mode:0},
{chapterId:276,title:"Tyrion II", source:"Pentos", target:"Andalos", mode:0},
{chapterId:277,title:"The Merchant's Man", source:"Volantis", target:"Astapor", mode:1},
{chapterId:278,title:"Jon II", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:279,title:"Tyrion III", source:"Andalos", target:"Ghoyan Drohe", mode:0},
{chapterId:280,title:"Davos I", source:"Eastwatch", target:"White Harbor", mode:1},
{chapterId:281,title:"Jon III", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:282,title:"Daenerys II", source:"Meereen", target:"Dothraki Sea", mode:2},
{chapterId:283,title:"Reek I", source:"Winterfell", target:"Dreadfort", mode:0},
{chapterId:284,title:"Bran II", source:"Haunted Forest", target:"Cave of the Children of the Forest", mode:0},
{chapterId:285,title:"Tyrion IV", source:"Ghoyan Drohe", target:"Ny Sar", mode:0},
{chapterId:286,title:"Davos II", source:"White Harbor", target:"White Harbor", mode:0},
{chapterId:287,title:"Daenerys III", source:"Qarth", target:"Meereen", mode:1},
{chapterId:287,title:"Daenerys III", source:"Qarth", target:"Pentos", mode:1},
{chapterId:287,title:"Daenerys III", source:"Astapor", target:"Meereen", mode:0},
{chapterId:288,title:"Jon IV", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:289,title:"Tyrion V", source:"Ny Sar", target:"the Sorrows", mode:0},
{chapterId:290,title:"Davos III", source:"White Harbor", target:"White Harbor", mode:0},
{chapterId:291,title:"Reek II", source:"Dreadfort", target:"Moat Cailin", mode:0},
{chapterId:292,title:"Jon V", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:293,title:"Tyrion VI", source:"the Sorrows", target:"Selhorys", mode:0},
{chapterId:294,title:"Daenerys IV", source:"Meereen", target:"Meereen", mode:0},
{chapterId:295,title:"The Lost Lord", source:"Selhorys", target:"Volon Therys", mode:0},
{chapterId:296,title:"The Windblown", source:"Astapor", target:"Yunkai", mode:0},
{chapterId:296,title:"The Windblown", source:"Yunkai", target:"Meereen", mode:0},
{chapterId:297,title:"The Wayward Bride", source:"Nagga's Hills", target:"Deepwood Motte", mode:1},
{chapterId:298,title:"Tyrion VII", source:"Selhorys", target:"Volantis", mode:0},
{chapterId:299,title:"Jon VI", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:300,title:"Davos IV", source:"White Harbor", target:"Skagos", mode:1},
{chapterId:301,title:"Daenerys V", source:"Astapor", target:"Meereen", mode:0},
{chapterId:302,title:"Melisandre I", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:303,title:"Reek III", source:"Moat Cailin", target:"Barrowton", mode:0},
{chapterId:304,title:"Tyrion VIII", source:"Volantis", target:"off the coast of Valyria", mode:1},
{chapterId:305,title:"Bran III", source:"Cave of the Children of the Forest", target:"Cave of the Children of the Forest", mode:0},
{chapterId:306,title:"Jon VII", source:"Castle Black", target:"Haunted Forest", mode:0},
{chapterId:307,title:"Daenerys VI", source:"Meereen", target:"Meereen", mode:0},
{chapterId:308,title:"The Prince of Winterfell", source:"Barrowton", target:"Winterfell", mode:0},
{chapterId:308,title:"The Prince of Winterfell", source:"Castle Black", target:"Winterfell", mode:0},
{chapterId:309,title:"The Watcher", source:"King's Landing", target:"Sunspear", mode:0},
{chapterId:310,title:"Jon VIII", source:"Castle Black", target:"Hardhome", mode:0},
{chapterId:311,title:"Tyrion IX", source:"off the coast of Valyria", target:"Gulf of Grief", mode:1},
{chapterId:312,title:"The Turncloak", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:313,title:"The King's Prize", source:"Deepwood Motte", target:"Village between the lakes", mode:0},
{chapterId:314,title:"Daenerys VII", source:"Meereen", target:"Meereen", mode:0},
{chapterId:315,title:"Jon IX", source:"Eastwatch", target:"Castle Black", mode:0},
{chapterId:315,title:"Jon IX", source:"Castle Black", target:"Nightfort", mode:0},
{chapterId:316,title:"The Blind Girl", source:"Braavos", target:"Braavos", mode:0},
{chapterId:316,title:"The Blind Girl", source:"Lys", target:"Hardhome", mode:1},
{chapterId:317,title:"A Ghost in Winterfell", source:"Winterfell", target:"Winterfell", mode:0},
{chapterId:318,title:"Tyrion X", source:"Gulf of Grief", target:"Meereen", mode:1},
{chapterId:319,title:"Jaime I", source:"Riverrun", target:"Raventree Hall", mode:0},
{chapterId:319,title:"Jaime I", source:"Raventree Hall", target:"Pennytree", mode:0},
{chapterId:320,title:"Jon X", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:320,title:"Jon X", source:"Eastwatch", target:"Hardhome", mode:1},
{chapterId:321,title:"Daenerys VIII", source:"Yunkai", target:"Meereen", mode:0},
{chapterId:321,title:"Daenerys VIII", source:"New Ghis", target:"Meereen", mode:1},
{chapterId:322,title:"Theon I", source:"Winterfell", target:"Wolfswood", mode:0},
{chapterId:323,title:"Daenerys IX", source:"Meereen", target:"Meereen", mode:0},
{chapterId:324,title:"Jon XI", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:325,title:"Cersei I", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:326,title:"The Queensguard", source:"Meereen", target:"Meereen", mode:0},
{chapterId:327,title:"The Iron Suitor", source:"Shield Islands", target:"Isle of Cedars", mode:1},
{chapterId:328,title:"Tyrion XI", source:"Meereen", target:"Meereen", mode:0},
{chapterId:329,title:"Jon XII", source:"Hardhome", target:"Castle Black", mode:0},
{chapterId:330,title:"The Discarded Knight", source:"Meereen", target:"Meereen", mode:0},
{chapterId:331,title:"The Spurned Suitor", source:"Meereen", target:"Meereen", mode:0},
{chapterId:332,title:"The Griffin Reborn", source:"Volon Therys", target:"Cape Wrath", mode:1},
{chapterId:333,title:"The Sacrifice", source:"Wolfswood", target:"Village between the lakes", mode:0},
{chapterId:334,title:"Victarion I", source:"Isle of Cedars", target:"Slaver's Bay", mode:1},
{chapterId:335,title:"The Ugly Little Girl", source:"Braavos", target:"Braavos", mode:0},
{chapterId:336,title:"Cersei II", source:"King's Landing", target:"King's Landing", mode:0},
{chapterId:337,title:"Tyrion XII", source:"Meereen", target:"Meereen", mode:0},
{chapterId:338,title:"The Kingbreaker", source:"Meereen", target:"Meereen", mode:0},
{chapterId:339,title:"The Dragontamer", source:"Meereen", target:"Meereen", mode:0},
{chapterId:340,title:"Jon XIII", source:"Castle Black", target:"Castle Black", mode:0},
{chapterId:341,title:"The Queen's Hand", source:"Meereen", target:"Meereen", mode:0},
{chapterId:342,title:"Daenerys X", source:"Meereen", target:"Dragonstone (Essos)", mode:0},
{chapterId:343,title:"Epilogue", source:"King's Landing", target:"King's Landing", mode:0}];

var nodes=[];
var links=[];
var nodeList=[];

travels.forEach(addLink);

function addLink(d,debug) {
	var s,t
	if((s=nodeList.indexOf(d.source))==-1) {
		//if(debug){console.log("adding node "+d.source);}
		nodeList.push(d.source);
		console.log(d.source);
		nodes.push({name:d.source,size:1,firstSeen:d.chapterId,lastSeen:d.chapterId,coords:regions[d.source].coords,region:regions[d.source].region,visits:[d.chapterId]});
		s=nodeList.indexOf(d.source)
	} else {
		//if(debug){console.log("new visit to "+d.source);}
		nodes[s].size++;
		nodes[s].visits.push(d.chapterId);
		nodes[s].lastSeen=d.chapterId;
	};
	if((t=nodeList.indexOf(d.target))==-1) {
		//if(debug){console.log("adding node "+d.target);}
		nodeList.push(d.target)
		nodes.push({name:d.target,size:1,firstSeen:d.chapterId,lastSeen:d.chapterId,coords:regions[d.target].coords,region:regions[d.target].region,visits:[d.chapterId]});
		t=nodeList.indexOf(d.target)
	} else {if(d.source!=d.target) {
		//if(debug){console.log("new visit to "+d.target);}
		nodes[t].size++;
		nodes[t].visits.push(d.chapterId);
		nodes[t].lastSeen=d.chapterId}
	};
	links.push({source:nodes[s],target:nodes[t],chapterId:d.chapterId,mode:d.mode});
}

var books=[
	{title:"A Game of Thrones",first:0,last:72},
	{title:"A Clash of Kings", first:73,last:142},
	{title:"A Storm of Swords",first:143,last:224},
	{title:"A Feast for Crows",first:225,last:270},
	{title:"A Dance with Dragons",first:271,last:343}
];

