      /*.transition()
      	.duration(totalDuration/12)
      	.delay(2*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,1);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(3*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,2);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(4*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,3);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(5*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,4);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(6*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,5);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(7*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,6);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(8*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,7);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(9*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,8);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(10*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,9);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(11*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,10);})
      .transition()
      	.duration(totalDuration/12)
      	.delay(12*totalDuration/12)
      	.style("fill",function(d,i){return colorMe(i,11);})*/
/*      
      
	      .transition()
	      .duration(totalDuration/12)
      	  .style("fill",function(d,i) {return colorMe(i,0);})
      	  .each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(0);};d3.select(this)
      	  		.transition()
	      		.duration(totalDuration/12)
      	  		.style("fill",function(d,i) {return colorMe(i,1);})
      	  		.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(1);};d3.select(this)
      	  			.transition()
	      			.duration(totalDuration/12)
      	  			.style("fill",function(d,i) {return colorMe(i,2);})
      	  			.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(2);};d3.select(this)
      	  				.transition()
	      				.duration(totalDuration/12)
      	  				.style("fill",function(d,i) {return colorMe(i,3);})
      	  				.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(3);};d3.select(this)
      	  					.transition()
	      					.duration(totalDuration/12)
      	  					.style("fill",function(d,i) {return colorMe(i,4);})
      	  					.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(4);};d3.select(this)
	      	  						.transition()
	      							.duration(totalDuration/12)
      	  							.style("fill",function(d,i) {return colorMe(i,5);})
      	  							.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(5);};d3.select(this)
      	  								.transition()
							      		.duration(totalDuration/12)
						      	  		.style("fill",function(d,i) {return colorMe(i,6);})
						      	  		.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(6);};d3.select(this)
						      	  			.transition()
								      		.duration(totalDuration/12)
							      	  		.style("fill",function(d,i) {return colorMe(i,7);})
							      	  		.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(7);};d3.select(this)
							      	  			.transition()
								      			.duration(totalDuration/12)
							      	  			.style("fill",function(d,i) {return colorMe(i,8);})
							      	  			.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(8);};d3.select(this)
							      	  				.transition()
								      				.duration(totalDuration/12)
							      	  				.style("fill",function(d,i) {return colorMe(i,9);})
							      	  				.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(9);};d3.select(this)
							      	  					.transition()
								      					.duration(totalDuration/12)
							      	  					.style("fill",function(d,i) {return colorMe(i,10);})
							      	  					.each("end",function() {if(d3.select(this).attr("id")=="FRA"){console.log(10);};d3.select(this)
								      	  						.transition()
								      							.duration(totalDuration/12)
							      	  							.style("fill",function(d,i) {return colorMe(i,11);})
														      	  							
						      	  						})	
						    			  	  		})	
						      	  				})	
						      	  			})		
						      	  		})	
						      	  	})	
      	  						})	
    			  	  		})	
      	  				})	
      	  			})		
      	  		})	
*/
